### ISSUE TITLE
Plugin still maintained?

### ISSUE THREAD

**Issue by verygoodplugins** [gravityplus/Gravity-Forms-Infusionsoft#13]
Hey there,

I've used this plugin a couple of years ago and found it to be helpful, but I was just contacted by an Infusionsoft partner saying that people are posting around Facebook that they're having a lot of trouble getting it to work at all. I see that there haven't been any updates in two years and it doesn't seem to be actively supported. I'm the lead developer of WP Fusion (https://wpfusionplugin.com/) and we offer a similar integration with Gravity Forms, but part of a larger package of integrations, at a price that's not affordable for people just looking to connect GForms to IS.

I wanted to ask if you're still maintaining this project, and if not, would you be willing to hand over the WP plugin repo so we could fix it and support it? We'd use our already written system for connecting GForms to Infusionsoft (https://wpfusionplugin.com/documentation/integrations/gravity-forms/), but keep it as a free plugin on the plugin repo, and include a link in the plugin inviting people to upgrade to the full version of WP Fusion for more features like content restriction, user registration and meta sync, tracking site activity, etc. We'd write a migration script to move over the existing settings format to the new format on upgrade.

Let me know what you think, thanks.

Jack Arturo

**Comment by naomicbush** [comment]
Hi @verygoodplugins, please point people here:

[Gravity Forms Infusionsoft Update](https://gravityplus.pro/gravity-forms-infusionsoft/?utm_source=github&utm_medium=link&utm_content=issue13&utm_campaign=gravity-forms-infusionsoft)

Also, would love to chat about how we might be able to work together. My contact information's on the website.
